-- Phase 2+: additive market-intelligence schema.
--
-- Migration 001_schema.sql owns the canonical definitions for market_quote,
-- price_bar, portfolio_snapshot, risk_profile, recommendation_run,
-- recommendation_item, and provider_health.  Earlier versions of this
-- migration attempted to recreate those tables with a second,